#!/bin/bash

backup_files="/home" # files to backup

dest="/media/elias/2BF1-71B2" # backup destination

if [ ! -d $dest ]; then
	echo "Error: Backupdrive is not mounted!"
else
	echo "Starting backup script"
	echo

	date=$(date +"%d-%m-%Y")
	hostname=$(hostname -s)
	archive_file="$hostname-$date.tgz"

	echo "Backing up $backup_files to $dest/$archive_file"
	date
	echo

	tar czf $dest/$archive_file $backup_files

	echo
	echo "Backup finished"
	date
	echo

	ls -lh $dest
fi
